Change case of "objectLiteral.hbs" so it can be found on Mac/Linux
I was getting the following error while trying to use this plugin:

Using TypeScript 2.3.2 from /home/gareth/dev/director-api-client/node_modules/typedoc/node_modules/typescript/lib
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/gareth/dev/director-api-client/node_modules/typedoc-plugin-markdown/dist/theme/partials/member.objectliteral.hbs'

It seems that typedoc was looking for a file 'member.objectliteral.hbs' instead of 'member.objectLiteral.hbs'. This wouldn't cause a problem on Windows, but breaks Mac/Linux. Renaming the file inside my node_modules fixed the problem.